[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.54.0"

[context.deploy-preview]
  command = "npm run build-preview"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.54.0"